### ISSUE TITLE
Databend Vector Stores

### ISSUE THREAD

**Issue by buhe** [buhe/langchain-swift#29]
https://www.databend.com/apply/

I am at that waitlist...

**Comment by buhe** [comment]
https://databend.rs/doc/sql-functions/ai-functions/

Vector store support is great, but generating embedding requires the AI_EMBEDDING_VECTOR function, which is too coupled.

**Comment by BohuTANG** [comment]
Thanks for mentioning.

> Only use OpenAI service.

Databend currently only provides support for OpenAI, but there is potential for adding other LLM models in the future.

> Vector store support is great, but generating embedding requires the AI_EMBEDDING_VECTOR function, which is too coupled.

Still confused with `too coupled`(Also we talked in email), here is some explains:
`AI_EMBEDDING_VECTOR` is a function that returns only a vector (of [ARRAY data type](https://databend.rs/doc/sql-reference/data-types/data-type-array-types)). This means you can store the resulting array in the Databend ARRAY data type or any other persistent ARRAY storage.
```
Query:select ai_embedding_vector('hi');

Result: [-0.03512698,-0.020624293,-0.015343423,-0.039803572,... <4096 items>]
```
Please inform me of your preferred version for `decoupling`.

**Comment by buhe** [comment]
If embedding and storage are separate, then I understand it wrong.

**Comment by BohuTANG** [comment]
Yes, they are separate, you can only utilize the `AI_EMBEDDING_VECTOR` function to get the vector array and save it to other stores.

**Comment by buhe** [comment]
Thank you for your answer.
