### ISSUE TITLE
env.txt Security

### ISSUE THREAD

**Issue by nbmisen** [buhe/langchain-swift#30]
大佬能不能把API Key改成初始化注入之类的形式，在工程文件里感觉不安全啊，怕被人解包什么的，谢谢

**Comment by buhe** [comment]
Sorry, please use English, although I am also a Chinese, but hope this project is international.

Ask, how to inject safer? In the form of a string?

**Comment by buhe** [comment]
Like: 
```
env["some_key"] = xxx
```
?

BR

buhe

**Comment by nbmisen** [comment]
Sorry about my Chinese description.
Yeah, you can make env a struct or class, we can configure it and make it safer by ourselves.

**Comment by buhe** [comment]
OK, thank you for the advice.

**Comment by buhe** [comment]
Please use 0.25.0+.
```
Env.initSet(["some_key": "some_value"])

// As some as before
```

Will merge env.txt when has it, otherwise use variable.
