### ISSUE TITLE
LangChain Module not found 

### ISSUE THREAD

**Issue by williamrct** [buhe/langchain-swift#6]
So I see that the Share app has a version of 0.7.0 while the git version is 0.16.0 and I am unable to build my app as it cannot find LangChain although the package is there.

Appreciate the help....

**Comment by buhe** [comment]
HI, Which project did you fail to build, and what was the error?

**Comment by buhe** [comment]
Because SPM uses git tags as versions, 0.7.0 and 0.16.0 are available versions, and 0.16.0 is newer than 0.7.0.

**Comment by williamrct** [comment]
I am using version 0.16.0 anf the error is LangChain module not found.  One notable difference is that you are using LangChain in the Share app for the Share Extension.  My use case is slightly different in that I want to use it directly from my app.  I declare an NSObject class where I import LangChain.  When I build I get the module not found error.  In my langchain-swift package the LangChain.swift file only contains: 

//
//  File.swift
//  
//
//  Created by 顾艳华 on 2023/6/11.
//

import Foundation

**Comment by williamrct** [comment]
BTW, thanks for the response much appreciated

**Comment by williamrct** [comment]
I am trygin to open the Writer project to see how you are using LangChain there but I am getting that you used a future version of xcode... probably beta.  Please let me know what version of xcode I can use to view the Writer project. Thanks

**Comment by buhe** [comment]
Sorry, I resubmitted writer_public using the local version of langchain-swift. BTW, if there is only one file in the dependent lc-swift you can try to delete and add it again.

**Comment by buhe** [comment]
You can create a blank project and just depend on langchain-swift.

**Comment by williamrct** [comment]
Thanks ... I am passed the issues I was having after clearing cache and derived data etc.

**Comment by williamrct** [comment]
OK good to know ... thanks

**Comment by buhe** [comment]
Is there anything I can do to help.

**Comment by williamrct** [comment]
Yes... thank you.... I see the openai is using chatgpt 3.5 turbo... can I use chatgpt 4?  I have more questions but this is good for now

**Comment by williamrct** [comment]
thanks

**Comment by buhe** [comment]
sure,please use version 0.16.0+.
```
import OpenAIKit

let llm = OpenAI(model: Model.GPT4.gpt4)
```
