### ISSUE TITLE
Supabase insert errors

### ISSUE THREAD

**Issue by Tobaibrahim** [buhe/langchain-swift#7]
I'm getting errors when using Supabase, I don't know what `### Insert Error: unacceptableStatusCode(400)` this error means, I assume it's related to inserting data to my database. It would be nice if you also showed how your Supabase database is setup. if you can lead me in the right direction it would be much appreciated. Also adding some localised description of this error would help better debug - ` ### RPC Error: unacceptableStatusCode(404)`

**Comment by buhe** [comment]
An https://github.com/buhe/langchain-swift/blob/main/Sources/LangChain/vectorstores/supabase.sql is required. Sorry I didn't add to the doc

ref: https://supabase.com/docs/guides/database/extensions/pgvector

**Comment by Tobaibrahim** [comment]
Thanks, it's all working now!

**Comment by buhe** [comment]
NP, feel free open this issue again ;)
