### ISSUE TITLE
Ollama support

### ISSUE THREAD

**Issue by gregorym** [buhe/langchain-swift#83]

**Comment by buhe** [comment]
Hey, Ollama focus on local model, and this lib(https://github.com/buhe/langchain-swift) current not support it.

FYI, https://github.com/buhe/langchain-swift/issues/40

**Comment by buhe** [comment]
Ollama has remote API, maybe use it.

**Comment by buhe** [comment]
Please use LMStudio API #86 ,feel free to open again.

**Comment by rhx** [comment]
Given that a lot of people are using Ollama and LMStudio cannot easily share models with Ollama, it might be worth reconsidering Ollama support.  I have been working on this and will send through a pull request soon.
