### ISSUE TITLE
Is there a plan to replace OpenAIKit?

### ISSUE THREAD

**Issue by Lavanille777** [buhe/langchain-swift#88]
It hasn't had any significant updates in a long time and doesn't even support the updates from version 1106.

**Comment by buhe** [comment]
Please, do you have any recommendations?

**Comment by Lavanille777** [comment]
> Please, do you have any recommendations?

I'm currently using the repository https://github.com/MacPaw/OpenAI, not sure if there might be a better alternative. Compared to the OpenAIKit, they offer support for function calling and the recent 1106 series of models. Even though the newest content format isn't yet supported, it's evident that there are already some people making efforts to adapt it.

**Comment by buhe** [comment]
I also used it at first, but I couldn't find how to set up proxy url. This is very important for blocked areas, such as China, because end users cannot be required to use VPN.

**Comment by Lavanille777** [comment]
> I also used it at first, but I couldn't find how to set up proxy url. This is very important for blocked areas, such as China, because end users cannot be required to use VPN.

Actually, you can set up a proxy server, just need to override the `buildURL(path: String)` method in `OpenAI.swift`. Although it requires modifying the source code, it's not complicated.

**Comment by buhe** [comment]
My previous project was to modify his source code. If you are willing, please submit a PR to it, thank you.

**Comment by Lavanille777** [comment]
> My previous project was to modify his source code. If you are willing, please submit a PR to it, thank you.

sure, I'll try it later.

**Comment by Lavanille777** [comment]
> My previous project was to modify his source code. If you are willing, please submit a PR to it, thank you.

Can you specify which repo it is?

**Comment by buhe** [comment]
Sure, https://github.com/buhe/OpenClient

**Comment by SteveCutler** [comment]
Any progress on this? Also would like to use the new preview model

**Comment by buhe** [comment]
@SteveCutler @Lavanille777 What new models are needed?

**Comment by buhe** [comment]
I fork that repo and add "gpt-4-1106-preview", "gpt-3.5-turbo-1106", wait original repo merged.

**Comment by SteveCutler** [comment]
> I fork that repo and add "gpt-4-1106-preview", "gpt-3.5-turbo-1106", wait original repo merged. I use my fork version on main branch first.

Thanks thats very helpful!

**Comment by buhe** [comment]
Please use 0.47.0

**Comment by SteveCutler** [comment]
Got it working, thank you very much

**Comment by buhe** [comment]
Feel free to open again.
