### ISSUE TITLE
Hello Everyone,

### ISSUE THREAD

**Issue by nishantminerva** [buhe/langchain-swift#9]
I am new to IOS Development, I saw a Youtube tutorial of - [how to make a pdf Q&A bot with python](https://www.youtube.com/watch?v=dXxQ0LR-3Hg&t=1551s). I wanted to make an IOS app of that. I find this langchain swift repository - but cause I  am very new I am having difficulties understanding this - please help me to understand this.

**Comment by buhe** [comment]
hi, 
You can easy use
```swift
let loader = TextLoader(file_path: "state_of_the_union.txt")
let documents = loader.load()
let text_splitter = CharacterTextSplitter(chunk_size: 1000, chunk_overlap: 0)

let embeddings = OpenAIEmbeddings()
let s = Supabase(embeddings: embeddings)
Task {
    for text in documents {
        let docs = text_splitter.split_text(text: text.page_content)
        for doc in docs {
            await s.addText(text: doc)
        }
    }
    
    let m = await s.similaritySearch(query: "What did the president say about Ketanji Brown Jackson", k: 1)
    print("Q:What did the president say about Ketanji Brown Jackson")
    print("A:\(m)")
}
```
and PDFLoader replace TextLoader.

buhe

**Comment by buhe** [comment]
Read it https://github.com/buhe/langchain-swift#get-stated , QA bot section please.

**Comment by buhe** [comment]
Please tell us where the document is not clear, so that it is easier to optimize the document.

**Comment by nishantminerva** [comment]
Thank you @buhe 
I don't know how to set up Supabase in IOS ,  please guide me.

**Comment by buhe** [comment]
hey,
https://github.com/buhe/langchain-swift#get-stated , QA bot section has detail.

**Comment by nishantminerva** [comment]
I am. really sorry if I am asking stupid questions again and again. Let  me know how I can contribute to this projects.

My question is that : - I create an IOS App then I imported this langchain-swift package using Swift Package Manager. Now I don't know how to configure(set up Supabase). I am also seeing that Xcode does not detects env in scope.

![Screenshot 2023-09-03 at 12 44 05 PM](https://github.com/buhe/langchain-swift/assets/53352011/18074761-385c-43c3-8421-ad6824747b55)

**Comment by buhe** [comment]
1. Setup supabase reference:

An [main/Sources/LangChain/vectorstores/supabase/supabase.sql](https://github.com/buhe/langchain-swift/blob/main/Sources/LangChain/vectorstores/supabase/supabase.sql) is required.

ref: https://supabase.com/docs/guides/database/extensions/pgvector

2. You don't need to  specified env, just put env.txt in the root directory, and the framework will try to find it itself.
 ref: https://github.com/buhe/Writer_public

Hope it will be useful.

**Comment by buhe** [comment]
Just
```
OpenAI()
```

**Comment by buhe** [comment]
If you have any questions, please feel free to ask.

**Comment by buhe** [comment]
Is there anything I can do to help?
