### ISSUE TITLE
Get Location Tool can't access GPS location

### ISSUE THREAD

**Issue by SteveCutler** [buhe/langchain-swift#96]
When I test the get location tool on its own by triggering the _run function with the arg "here" it accurately provides out the simulator GPS latitude and longitude, but when the agent uses the tool it says something like "You are currently at the location with the latitude and longitude values provided by the GetLocation tool." instead of providing the lat and long values.

I added permission in my info.plist for location access and when I run the function manually with a tesrt button the Location symbol shows up in the top bar that shows when its' accessing your location, but when Langchain uses the tool the symbol does not show up, which leads me to believe that it does not have permission to access the location for some reason.

At first it was just providing the example lat and long values given in the tool description but then I edited it in my fork to display 'Returns the current numerical latitude and longitude values in this format "Latitude, Longitude"'

**Comment by buhe** [comment]
Can you provide a minimum reproduction project?

**Comment by SteveCutler** [comment]
Yes will do tomorrow morning! 
That's when I just create a stripped down version of the project for testing purposes, correct?
Still very new to this..

**Comment by buhe** [comment]
Okey. Nice.

**Comment by SteveCutler** [comment]
Nevermind, either your new version fixed this or more likely I messed something up in the process of exploration.
thanks!

**Comment by SteveCutler** [comment]
non-issue

**Comment by SteveCutler** [comment]
My mistake - it is still not working. At first it provides the example coordinates from the getlocations.swift file tool prompt "Tool of get current location.
        Input must be "here".
        Returns the current longitude and latitude, such as -78.4:38.5."
        
and I mistook them for my actual location, but when I reformatted the description to read 

"Tool of get current location.
        Input must be "here".
        Returns the current latitude and longitude in the form: "lat, long".
        
It defaults to providing the coordinates for City Hall in NYC
"40.7128, -74.0060"

Again I think this must be a permissions issue or something because I can run the tool manually perfectly fine and get my accurate location coordinates.
Will upload a minimum reproduction project later!

**Comment by SteveCutler** [comment]
Fixed it 
In the end I was using ChatOpenAI instead of OpenAI as the llm and that seems to have been causing the problem. All good.

**Comment by buhe** [comment]
Congratulate!
Do I need to change anything?

**Comment by SteveCutler** [comment]
> Congratulate! Do I need to change anything?

No sir!
