### ISSUE TITLE
generative-ai-swift and Gemini.swift fail

### ISSUE THREAD

**Issue by SteveCutler** [buhe/langchain-swift#97]
These always fail for me on build so I have to comment out generativeAI from package.swift and delete the gemini.swift file from LLMs in my fork, may be because I'm in Canada and Gemini isn't available here - just a heads up.

**Comment by buhe** [comment]
Can you access https://github.com/google/generative-ai-swift?

**Comment by SteveCutler** [comment]
Yes I can

**Comment by buhe** [comment]
I asked friends from different networks to help test it, and they were able to do it. Can you provide details?

**Comment by SteveCutler** [comment]
Hmm it seems to be working now, although it was giving me an error yesterday. 
False alarm I guess!
