### ISSUE TITLE
Issue with Async-http-client package for WatchOS app

### ISSUE THREAD

**Issue by SteveCutler** [buhe/langchain-swift#98]
When I test my watchOS app on the simulator the network call works fine but when I test on the real device it appears there's an issue with this 'Async-http-client'package.

in HTTPHandler.swift this line:
    static let maxByteBufferSize = Int(UInt32.max)

crashes the app,

when I replace it with:
        static let safeMaxBufferSize: Int = {
        if MemoryLayout<Int>.size == MemoryLayout<UInt32>.size {
            // 32-bit system - use Int32.max
            return Int(Int32.max)
        } else {
            // 64-bit system - using UInt32.max is safe
            return Int(UInt32.max)
        }
    }()

    static let maxByteBufferSize = safeMaxBufferSize

it no longer crashes the app but the network call to OpenAI still fails.

When I tested the iOS version of my app on the real device it works no problem. Not sure where the issue could be coming from.

Where is this 'Async-http-client' package sourced from?

**Comment by SteveCutler** [comment]
The exact error I get once I've changed this line is:

LLM generate The operation couldn’t be completed. (NIOPosix.NIOConnectionError error 1.)

**Comment by buhe** [comment]
https://github.com/swift-server/async-http-client is a famous package.

Sorry, I can`t test on real device, can you provide details?

**Comment by SteveCutler** [comment]
where is it being sourced from in the dependencies though. I want to relink it to a forked version but its not in the package.swift file. It must be coming upstream from another package right?

I think it's only being used in the OpenAI.swift file for the engine call right?
Could I use Alamofire's functionality (or some other package) to do the same thing?

**Comment by buhe** [comment]
Yes.

**Comment by SteveCutler** [comment]
I fixed this issue by switching the openAI.swift file to use URL session like he recommends in the OpenAI-kit git repo Readme

**Comment by buhe** [comment]
Thanks, please review https://github.com/buhe/langchain-swift/pull/99

**Comment by buhe** [comment]
Until i buy apple watch at October :)

**Comment by SteveCutler** [comment]
This is what worked for me:

let urlSession = URLSession(configuration: .default)
let organization = ""
let configuration = Configuration(apiKey: apiKey, organization: organization)
let openAIClient = OpenAIKit.Client(session: urlSession, configuration: configuration)

**Comment by buhe** [comment]
Thanks, please review https://github.com/buhe/langchain-swift/pull/99
